### ISSUE TITLE
Roadmap to 2.0

### ISSUE THREAD

**Issue by cemkeylan** [CarbsLinux/kiss#3]
For 2.0 I plan certain changes that will cause a detach from the
KISS Linux environment. Some package manager API will be different
as well, so they should be documented well

~- [ ] ~Rename package manager.~
~- [ ] Rename `contrib` scripts.~
~- [ ] Switch `sys_db` location on kiss and contrib scripts~
- [x] Support a binary repository natively. -- [carbslinux/kiss-bin](https://github.com/CarbsLinux/kiss-bin)
- [ ] Support `rsync` repositories.
- [x] Ensure BSD Compatibility. - Tracking in #2 
- [x] Seperate post-install scripts and messages. Queue message files in a clean looking way.
